mainWindowTitle = "Tablet data presenter"
windowPadding = 20
buttonsTextPadding = (5, 5, 5, 5)
buttonsFont = "serif 10"
windowElementsHeight = 600
imageCanvasWidth = 600
buttonsFrameWidth = 200
loadFileButtonText = "Load file"
buttonsPadding = (0, 15)
dataXNumber = 1
dataYNumber = 2
redrawButtonText = "Redraw"